# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/the_assembler/Src/SpaceInvaders

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/the_assembler/Src/SpaceInvaders

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/the_assembler/Src/SpaceInvaders/CMakeFiles /home/the_assembler/Src/SpaceInvaders//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/the_assembler/Src/SpaceInvaders/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SpaceInvaders

# Build rule for target.
SpaceInvaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpaceInvaders
.PHONY : SpaceInvaders

# fast build rule for target.
SpaceInvaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/build
.PHONY : SpaceInvaders/fast

src/core/cpu.o: src/core/cpu.c.o
.PHONY : src/core/cpu.o

# target to build an object file
src/core/cpu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/cpu.c.o
.PHONY : src/core/cpu.c.o

src/core/cpu.i: src/core/cpu.c.i
.PHONY : src/core/cpu.i

# target to preprocess a source file
src/core/cpu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/cpu.c.i
.PHONY : src/core/cpu.c.i

src/core/cpu.s: src/core/cpu.c.s
.PHONY : src/core/cpu.s

# target to generate assembly for a file
src/core/cpu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/cpu.c.s
.PHONY : src/core/cpu.c.s

src/core/cpu_opcodes.o: src/core/cpu_opcodes.c.o
.PHONY : src/core/cpu_opcodes.o

# target to build an object file
src/core/cpu_opcodes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/cpu_opcodes.c.o
.PHONY : src/core/cpu_opcodes.c.o

src/core/cpu_opcodes.i: src/core/cpu_opcodes.c.i
.PHONY : src/core/cpu_opcodes.i

# target to preprocess a source file
src/core/cpu_opcodes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/cpu_opcodes.c.i
.PHONY : src/core/cpu_opcodes.c.i

src/core/cpu_opcodes.s: src/core/cpu_opcodes.c.s
.PHONY : src/core/cpu_opcodes.s

# target to generate assembly for a file
src/core/cpu_opcodes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/cpu_opcodes.c.s
.PHONY : src/core/cpu_opcodes.c.s

src/core/gpu.o: src/core/gpu.c.o
.PHONY : src/core/gpu.o

# target to build an object file
src/core/gpu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/gpu.c.o
.PHONY : src/core/gpu.c.o

src/core/gpu.i: src/core/gpu.c.i
.PHONY : src/core/gpu.i

# target to preprocess a source file
src/core/gpu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/gpu.c.i
.PHONY : src/core/gpu.c.i

src/core/gpu.s: src/core/gpu.c.s
.PHONY : src/core/gpu.s

# target to generate assembly for a file
src/core/gpu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/gpu.c.s
.PHONY : src/core/gpu.c.s

src/core/manager.o: src/core/manager.c.o
.PHONY : src/core/manager.o

# target to build an object file
src/core/manager.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/manager.c.o
.PHONY : src/core/manager.c.o

src/core/manager.i: src/core/manager.c.i
.PHONY : src/core/manager.i

# target to preprocess a source file
src/core/manager.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/manager.c.i
.PHONY : src/core/manager.c.i

src/core/manager.s: src/core/manager.c.s
.PHONY : src/core/manager.s

# target to generate assembly for a file
src/core/manager.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/manager.c.s
.PHONY : src/core/manager.c.s

src/core/mem.o: src/core/mem.c.o
.PHONY : src/core/mem.o

# target to build an object file
src/core/mem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/mem.c.o
.PHONY : src/core/mem.c.o

src/core/mem.i: src/core/mem.c.i
.PHONY : src/core/mem.i

# target to preprocess a source file
src/core/mem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/mem.c.i
.PHONY : src/core/mem.c.i

src/core/mem.s: src/core/mem.c.s
.PHONY : src/core/mem.s

# target to generate assembly for a file
src/core/mem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/core/mem.c.s
.PHONY : src/core/mem.c.s

src/entry.o: src/entry.c.o
.PHONY : src/entry.o

# target to build an object file
src/entry.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/entry.c.o
.PHONY : src/entry.c.o

src/entry.i: src/entry.c.i
.PHONY : src/entry.i

# target to preprocess a source file
src/entry.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/entry.c.i
.PHONY : src/entry.c.i

src/entry.s: src/entry.c.s
.PHONY : src/entry.s

# target to generate assembly for a file
src/entry.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/entry.c.s
.PHONY : src/entry.c.s

src/io/log.o: src/io/log.c.o
.PHONY : src/io/log.o

# target to build an object file
src/io/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/io/log.c.o
.PHONY : src/io/log.c.o

src/io/log.i: src/io/log.c.i
.PHONY : src/io/log.i

# target to preprocess a source file
src/io/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/io/log.c.i
.PHONY : src/io/log.c.i

src/io/log.s: src/io/log.c.s
.PHONY : src/io/log.s

# target to generate assembly for a file
src/io/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/io/log.c.s
.PHONY : src/io/log.c.s

src/tests/tests.o: src/tests/tests.c.o
.PHONY : src/tests/tests.o

# target to build an object file
src/tests/tests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/tests/tests.c.o
.PHONY : src/tests/tests.c.o

src/tests/tests.i: src/tests/tests.c.i
.PHONY : src/tests/tests.i

# target to preprocess a source file
src/tests/tests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/tests/tests.c.i
.PHONY : src/tests/tests.c.i

src/tests/tests.s: src/tests/tests.c.s
.PHONY : src/tests/tests.s

# target to generate assembly for a file
src/tests/tests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/src/tests/tests.c.s
.PHONY : src/tests/tests.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SpaceInvaders"
	@echo "... src/core/cpu.o"
	@echo "... src/core/cpu.i"
	@echo "... src/core/cpu.s"
	@echo "... src/core/cpu_opcodes.o"
	@echo "... src/core/cpu_opcodes.i"
	@echo "... src/core/cpu_opcodes.s"
	@echo "... src/core/gpu.o"
	@echo "... src/core/gpu.i"
	@echo "... src/core/gpu.s"
	@echo "... src/core/manager.o"
	@echo "... src/core/manager.i"
	@echo "... src/core/manager.s"
	@echo "... src/core/mem.o"
	@echo "... src/core/mem.i"
	@echo "... src/core/mem.s"
	@echo "... src/entry.o"
	@echo "... src/entry.i"
	@echo "... src/entry.s"
	@echo "... src/io/log.o"
	@echo "... src/io/log.i"
	@echo "... src/io/log.s"
	@echo "... src/tests/tests.o"
	@echo "... src/tests/tests.i"
	@echo "... src/tests/tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

